### ISSUE TITLE
Trying to install dependencies - npm not recognized

### ISSUE THREAD

**Issue by MPags02** [cis3296s24/Temple-Trading-Hub-Team1#19]
Process: I cloned the repo, opened a terminal window, cd to directory, then ran: "npm install @fontsource/your-font" as specified. I then recieved this message: "'npm' is not recognized as an internal or external command,
operable program or batch file."

There are no instructions on how/where to install npm, unable to test project.

**Comment by NasierF** [comment]
I see how this could have been confusing, we have changed the directions in our Readme. Thank you for the input!
