### ISSUE TITLE
Dependencies and Text

### ISSUE THREAD

**Issue by enesmance** [cis3296s24/Temple-Trading-Hub-Team1#28]
- The instructions for installing the dependencies may be mixed up, I'm on mac and tried the mac instructions and they didn't work on my end but I tried the instructions for other machines and it did.
- The text for the items and their condition roll off the boxes and make it hard to see with the background color
- Not sure if it's been implemented yet but the threads tab is not working

**Comment by NasierF** [comment]
Are you sure you had Node installed? Possibly your version of node was deprecated? I have tested the instructions on Mac and Windows and it works currently. We made a lot if UI fixes so the item text is no longer an issue. The threads tab is working at this moment, possibly there was a bug at the time. Thank you for your input!
